# ==============================================================================
# GLOBAL CONFIG SETTINGS
# ==============================================================================
global:
  pipeline_settings:
    project_name: "Catchment_Based_Groundwater_Forecasting"
    random_seed: 55  # Smooth operation
    log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
    catchments_to_process: ["eden"]  # TODO: add more in future dev
    run_defra_api: False
    run_camels_api: False
    run_outlier_detection: False
    run_gwl_imputation: False

  # --- FILE PATHS ---
  paths:
    # --- Specific INPUT files ---
    gis_os_grid_squares: "data/01_raw/global/os_grid_squares.csv"
    defra_station_base_url: "https://environment.data.gov.uk/hydrology/id/stations"
    # --- Specific OUTPUT files ---
      # currently none, remove in future if not used
    # --- Data Directories ---
    data_dir: "data/"
    raw_data_dir: "data/01_raw/"
    processed_data_dir: "data/02_processed/"
    external_data_dir: "data/03_external/"
    # --- Results Directories ---
    results_dir: "results/"
    logs_results_dir: "results/logs/"
    temp_results_dir: "results/temp_plots/"
    tables_results_dir: "results/tables/"
    figures_results_dir: "results/figures/"
    trained_model_results_dir: "results/trained_models/"
    predictions_results_dir: "results/predictions/"

  # --- DATA INGESTION SETTINGS ---
  data_ingestion:
    api_start_date: "2013-11-01T00:00:00"
    api_end_date: "2025-02-28T23:59:59"
    model_start_date: "2014-01-01T00:00:00"
    model_end_date: "2024-12-31T23:59:59"
    col_order: ['station_name', 'date', 'dateTime', 'value', 'quality', 'measure']
    max_interp_length: 25
  
  # --- PROPROCESSING SETTING ---
  preprocessing:
    radius: 6371000.0
    gap_lengths_days: [30, 60, 90, 120, 150]
    max_imputation_threshold: 200
    min_data_points_around_gap: 5

  # --- VISUALISATION SETTINGS ---
  visualisations:
    maps:
      display_interactive_map: True
      esri: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
      esri_attr: "Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ"
      map_blue: "#354c7c"
    
  # --- GRAPH CONSTRUCTION SETTINGS ---
  graph:
    data_point_quantity_threshold: 5000

  #   time_series_cleaning:
  #     interpolation_method: "linear"
  #     max_gap_to_interpolate_days: 7
  #   spatial_alignment:
  #     mesh_resolution_km: 5
  #     snapping_tolerance_m: 20
  #   graph_construction:
  #     graph_type: "k_nearest_neighbors" # Options: "k_nearest_neighbors", "delaunay_triangulation", etc.
  #     k_neighbors: 5
  #     edge_features_to_add: ["distance", "elevation_difference"]
  #   feature_engineering:
  #     add_time_of_year: true
  #     add_lagged_features: true
  #     lag_steps: [1, 7, 14, 30] # In days / time steps

  # # --- MODEL SETTINGS (for GAT-LSTM) ---
  # model:
  #   architecture: "GAT_LSTM"
  #   gat_layers: 2
  #   gat_heads: 4
  #   lstm_hidden_dim: 128
  #   dropout_rate: 0.2
  #   output_dim: 1

  # # --- TRAINING SETTINGS ---
  # training:
  #   epochs: 100
  #   batch_size: 32
  #   learning_rate: 0.001
  #   optimizer: "Adam"
  #   loss_function: "MSELoss"
  #   early_stopping:
  #     patience: 10
  #     min_delta: 0.0001
  #   device: "cuda" # or "cpu"

  # # --- EVALUATION SETTINGS ---
  # evaluation:
  #   metrics: ["RMSE", "MAE", "R2"]
  #   save_plots: true
  #   split_ratio: 0.2 # 80% train, 20% test
  #   target_variable: "groundwater_level" # The column the model is predicting

# ==============================================================================
# EDEN CATCHMENT CONFIG SETTINGS
# ==============================================================================

eden:
  # --- FILE PATHS ---
  paths:
    # --- Specific INPUT files ---
    gis_catchment_boundary: "data/01_raw/eden/gis/eden_catchment_boundary/NRFA_catchments.shp"
    gwl_station_list: "data/01_raw/eden/gwl_stations/station_list.csv"
    raw_land_cover_path: "data/01_raw/eden/static/land_cover/gb2023lcm1km_dominant_aggregate.tif"
    elevation_dir_path: "data/01_raw/eden/static/elevation/"
    # --- Specific OUPUT (processed) files ---
    mesh_nodes_output: "data/02_processed/eden/gis_and_mesh/catchment_mesh_nodes"  # ensure no specific file extension
    gwl_station_list_with_coords: "data/02_processed/eden/gwl_station_data/station_list_with_coords.csv"
    gwl_station_metadata_measures: "data/02_processed/eden/gwl_station_data/gwl_station_metadata_measures.csv"
    gwl_data_output_dir: "data/01_raw/eden/gwl_stations/API_data/"
    gwl_outlier_dict: "data/02_processed/eden/gwl_station_data/dict_witout_outliers.pkl"
    trimmed_output_dir: "data/02_processed/eden/gwl_timeseries/"
    land_cover_csv_path: "data/02_processed/eden/static/land_cover/land_cover.csv"
    elevation_tif_path: "data/02_processed/eden/static/elevation/elevation.tif"
    direction_edge_weights_path: "data/02_processed/eden/static/slope/direction_edge_weights.csv"
    slope_path: "data/02_processed/eden/static/slope/slope_magnitude_aspect.csv"
  
  # --- PREPROCESSING SETTINGS ---
  preprocessing:
    inclusion_threshold: 5000
    large_catchment_threshold_m: 50000
    dist_corr_score_k_decay: 0.05
    dist_corr_score_threshold: 0.3
    graph_construction:
      grid_resolution: 1000  # Potentially change to 500m grid
    catchment_max_elevation: 945.40  # mAOD from https://nrfa.ceh.ac.uk/data/station/spatial/76007
    catchment_min_elevation: 8.00  # mAOD from https://nrfa.ceh.ac.uk/data/station/spatial/76007
  
  visualisations:
    maps:
      static_mesh_map_output: "results/figures/eden/maps/static_mesh_map"  # ensure no specific file extension
      interactive_mesh_map_output: "results/figures/eden/maps/interactive_mesh_map"  # ensure no specific file extension
    ts_plots:
      time_series_gwl_output: "results/figures/eden/time_series/"
      dpi_save: 300  # Adjust to 300 for final output run
      extension: "svg"
    corr_dist_score_scatters: "results/figures/eden/scatter/"

# ==============================================================================
# FUTURE CATCHMENT CONFIG SETTINGS
# ==============================================================================

# Copy eden structure for full pipeline and adapt