# ==============================================================================
# GLOBAL CONFIG SETTINGS
# ==============================================================================
global:
  pipeline_settings:
    project_name: "Catchment_Based_Groundwater_Forecasting"
    random_seed: 55  # Smooth operation
    log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
    catchments_to_process: ["eden"]  # TODO: can easily add more in future dev
    run_defra_api: false
    run_camels_api: false
    run_era5_land_api: false  # Long!
    run_outlier_detection: false
    run_gwl_imputation: false

  # --- FILE PATHS ---
  paths:
    # --- Specific INPUT files ---
    gis_os_grid_squares: "data/01_raw/global/os_grid_squares.csv"
    defra_station_base_url: "https://environment.data.gov.uk/hydrology/id/stations"
    HAD_UK_rainfall_url: "https://dap.ceda.ac.uk/thredds/dodsC/badc/ukmo-hadobs/data/insitu/MOHC/HadOBS/HadUK-Grid/v1.3.0.ceda/1km/rainfall/day/v20240514/rainfall_hadukgrid_uk_1km_day_"
    CDSAPI_path: "~/Desktop/Dissertation_Code/.cdsapirc"
    # --- Specific OUTPUT files ---
      # currently none, remove in future if not used
    # --- Data Directories ---
    data_dir: "data/"
    raw_data_dir: "data/01_raw/"
    processed_data_dir: "data/02_processed/"
    external_data_dir: "data/03_external/"
    # --- Results Directories ---
    results_dir: "results/"
    logs_results_dir: "results/logs/"
    temp_results_dir: "results/temp_plots/"
    tables_results_dir: "results/tables/"
    figures_results_dir: "results/figures/"
    trained_model_results_dir: "results/trained_models/"
    predictions_results_dir: "results/predictions/"

  # --- DATA INGESTION SETTINGS ---
  data_ingestion:
    api_start_date: "2013-11-01T00:00:00"
    api_end_date: "2025-02-28T23:59:59"
    model_start_date: "2018-01-01T00:00:00"
    model_end_date: "2024-12-31T23:59:59"
    col_order: ['station_name', 'date', 'dateTime', 'value', 'quality', 'measure']
    max_interp_length: 25

  # --- PROPROCESSING SETTINGS ---
  preprocessing:
    radius: 6371000.0
    gap_lengths_days: [30, 60, 90, 120, 150]
    max_imputation_threshold: 200
    min_data_points_around_gap: 5

  # --- VISUALISATION SETTINGS ---
  visualisations:
    maps:
      display_interactive_map: true
      esri: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
      esri_attr: "Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ"
      map_blue: "#354c7c"

  # --- GRAPH CONSTRUCTION SETTINGS ---
  graph:
    data_point_quantity_threshold: 5000
    graph_construction:
      graph_type: "grid_adjacency"  # Otherwise: "k_nearest_neighbors", "delaunay_triangulation", etc.
      k_neighbors: 8  # Basic Surrounding Grid
    sentinel_value: -999.0  # Float to match col dtypes
    epsilon: 1e-6

  # --- MODEL SETTINGS (for GAT-LSTM) ---
  model:
    data_loader_batch_size: 1  # Necessary due to LSTM portion
    data_loader_shuffle: false  # Essential for processing in temporal order
    architecture: "GAT_LSTM"
    gat_layers: 2
    gat_heads: 4
    lstm_hidden_dim: 128
    dropout_rate: 0.2
    output_dim: 1

  # # --- TRAINING SETTINGS ---
  # training:
  #   epochs: 100
  #   batch_size: 32
  #   learning_rate: 0.001
  #   optimizer: "Adam"
  #   loss_function: "MSELoss"
  #   early_stopping:
  #     patience: 10
  #     min_delta: 0.0001
  #   device: "cuda" # or "cpu"

  # # --- EVALUATION SETTINGS ---
  # evaluation:
  #   metrics: ["RMSE", "MAE", "R2"]
  #   save_plots: true
  #   split_ratio: 0.2 # 80% train, 20% test
  #   target_variable: "gwl_value" # Target Column: Groundwater Level

# ==============================================================================
# EDEN CATCHMENT CONFIG SETTINGS
# ==============================================================================

eden:
  target_mncat: "Eden and Esk"

  # --- FILE PATHS ---
  paths:
    # --- Specific INPUT files ---
    # gis_catchment_boundary: "data/01_raw/eden/gis/eden_catchment_boundary/NRFA_catchments.shp"
    gis_catchment_boundary: "data/01_raw/eden/gis/eden_catchment_boundary/WFD_Surface_Water_Operational_Catchments_Cycle_2.shp"
    gis_catchment_dir: "data/01_raw/eden/gis/eden_catchment_boundary/"
    gwl_station_list: "data/01_raw/eden/gwl_stations/station_list.csv"
    raw_land_cover_path: "data/01_raw/eden/static/land_cover/gb2023lcm1km_dominant_aggregate.tif"
    elevation_dir_path: "data/01_raw/eden/static/elevation/"
    rainfall_filename_dir: "data/01_raw/eden/hydroclimatic/rainfall/"

    # --- Specific OUPUT (processed) files ---
    mesh_nodes_output: "data/02_processed/eden/gis_and_mesh/catchment_mesh_nodes"  # ensure no specific file extension
    gwl_station_list_with_coords: "data/02_processed/eden/gwl_station_data/station_list_with_coords.csv"
    gwl_station_list_output: "data/02_processed/eden/gwl_station_data/updated_station_list_with_coords.csv"
    gwl_station_metadata_measures: "data/02_processed/eden/gwl_station_data/gwl_station_metadata_measures.csv"
    snapped_station_node_mapping: "data/02_processed/eden/gwl_station_data/snapped_station_node_mapping.csv"
    gwl_data_output_dir: "data/01_raw/eden/gwl_stations/API_data/"
    gwl_outlier_dict: "data/02_processed/eden/gwl_station_data/dict_witout_outliers.pkl"
    trimmed_output_dir: "data/02_processed/eden/gwl_timeseries/"
    land_cover_csv_path: "data/02_processed/eden/static/land_cover/land_cover.csv"
    elevation_tif_path: "data/02_processed/eden/static/elevation/elevation.tif"
    direction_edge_weights_path: "data/02_processed/eden/static/slope/direction_edge_weights.csv"
    slope_path: "data/02_processed/eden/static/slope/slope_magnitude_aspect.csv"
    aet_raw_output_dir: "data/01_raw/eden/hydroclimatic/aet/"
    output_polygon_dir: "data/02_processed/eden/gis/"
    elevation_geojson_path: "data/02_processed/eden/static/elevation/elevation.geojson"
    geology_dir: "data/01_raw/eden/static/geology"
    permeability_dir: "data/01_raw/eden/static/permeability"
    geology_df: "data/02_processed/eden/static/geology"

    # --- ERA5-Land API Ingestion ---
    aet_processed_output_dir: "data/02_processed/eden/hydroclimatic/aet/"
    2t_raw_output_dir: "data/01_raw/eden/hydroclimatic/2meter_temp/"
    2t_processed_output_dir: "data/02_processed/eden/hydroclimatic/2meter_temp/"
    sp_raw_output_dir: "data/01_raw/eden/hydroclimatic/surface_pressure/"
    sp_processed_output_dir: "data/02_processed/eden/hydroclimatic/surface_pressure/"
    aet_csv_path: "data/02_processed/eden/hydroclimatic/aet/aet_daily_catchment_sum.csv"
    aet_fig_path: "results/figures/eden/time_series/hydroclimatic/aet_timeseries.png"
    2t_csv_path: "data/02_processed/eden/hydroclimatic/2meter_temp/2m_temp_daily_catchment_mean.csv"
    2t_fig_path: "results/figures/eden/time_series/hydroclimatic/2m_temp_timeseries.png"
    sp_csv_path: "data/02_processed/eden/hydroclimatic/surface_pressure/surface_pressure_daily_catchment_mean.csv"
    sp_fig_path: "results/figures/eden/time_series/hydroclimatic/surface_pressure_timeseries.png"

    # --- HAD-UK data ingestion ---
    rainfall_processed_output_dir: "data/02_processed/eden/hydroclimatic/rainfall/"
    rainfall_fig_path: "results/figures/eden/time_series/hydroclimatic/rainfall_volume_timeseries.png"
    rainfall_csv_path: "data/02_processed/eden/hydroclimatic/rainfall/rainfall_daily_catchment_sum_log_transform.csv"

    # --- Graph Paths ---
    final_df_path: "data/02_processed/eden/final_df/"
    graph_data_output_dir: "data/03_graph/eden/tensors/"
    pyg_object_path: "data/03_graph/eden/PyG/all_timesteps_list.pt"
    scalers_dir: "data/03_graph/eden/scalers/"

    # --- Model Paths ---
    best_model_path: "data/04_model/eden/model/best_model.pt"
    model_dir: "data/04_model/eden/model/"

  # --- PREPROCESSING SETTINGS ---
  preprocessing:
    inclusion_threshold: 5000
    large_catchment_threshold_m: 50000
    dist_corr_score_k_decay: 0.05
    dist_corr_score_threshold: 0.3
    graph_construction:
      grid_resolution: 1000  # Could change to 500m grid in future for performance. Will require pipeline adjustments.
    catchment_max_elevation: 945.40  # mAOD from https://nrfa.ceh.ac.uk/data/station/spatial/76007
    catchment_min_elevation: 8.00  # mAOD from https://nrfa.ceh.ac.uk/data/station/spatial/76007
    # --- Generated in Pipeline ---
    rainfall_boxcox_lambda: 0.1701496697839992
    aet_boxcox_lambda: 0.4931417208883217
    mean_elevation_boxcox_lambda: 0.43791794465031564
    mean_slope_deg_boxcox_lambda: -0.24587351671403726

  # --- VISUALISATION OUTPUT SETTINGS ---
  visualisations:
    maps:  # ensure no specific file extensions here
      static_mesh_map_output: "results/figures/eden/maps/static_mesh_map"
      interactive_mesh_map_output: "results/figures/eden/maps/interactive_mesh_map"
      interactive_station_map_output: "results/figures/eden/maps/interactive_station_mesh_map"
      interactive_directional_map_output: "results/figures/eden/maps/interactive_directional_map"
    ts_plots:
      time_series_gwl_output: "results/figures/eden/time_series/"
      dpi_save: 300  # Always adjust to 300 for final output run
      extension: "svg"
    corr_dist_score_scatters: "results/figures/eden/scatter/"
    violin_plt_path: "results/figures/eden/other/standardised_violins.png"

  # --- GRAPH CONSTRUCTION SETTINGS ---
  model:
    architecture:
      # --- GAT ---
      run_GAT: True  # Turn sections off for benchmarking and performance analysis
      heads_gat: 8 # (2) - to 8, then 4
      dropout_gat: 0.4  # 40% dropped - (1) To 0.4 next
      hidden_channels_gat: 64
      out_channels_gat: 64
      num_layers_gat: 2
      # --- LSTM ---
      run_LSTM: False
      hidden_channels_lstm: 64  # (3) - reduce to 32
      num_layers_lstm: 2  # stack layers later if needed for performance
      # --- Full Model ---
      output_dim: 1  # one station gwl prediction per timestep
      adam_learning_rate: 0.001
      adam_weight_decay: 0.001  # 5e-4 is common initial weight decay val - (0) currenlty 0.005 to 0.001
    data_partioning:
      test_station_shortlist: ["ainstable", "coupland", "scaleby"]  # Length ideally >= minimum station req count
      val_station_shortlist: ["castle_carrock", "skirwith", "great_musgrave"]  # Length ideally >= minimum station req count
      percentage_train: 77
      percentage_val: 15  # 2 stations for validating
      percentage_test: 8  # 1 station tested at a time
      len_train: 11
      len_val: 2
      len_test: 1

  # --- MODEL IMPLEMENTATION SETTINGS ---
  training:
    verbose: true  # Run logger to debug (increases computation)
    num_epochs: 200  # Start here, may need to increase depending on computation times
    early_stopping_patience: 15  # Early Stopping: Number of epochs to wait for improvement in validation loss before stopping training.
    lr_scheduler_factor: 0.5  # ReduceLROnPlateau: Factor by which the learning rate will be reduced.
    lr_scheduler_patience: 5  # Patience for ReduceLROnPlateau: Number of epochs with no improvement in validation
    min_lr: 0.000001  # Min learning rate bound (Generally recommended: 1e-6)
    loss_delta: 0.0001  # Minimum change in loss required to count as improvement
    gradient_clip_max_norm: 1.0  # Gradient Clipping Max Norm: Maximum norm of the gradients for gradient clipping (help prevent exploding grad.)
    loss: "MAE"  # Options: MSE, MAE

# ==============================================================================
# FUTURE CATCHMENT CONFIG SETTINGS
# ==============================================================================

# Copy eden structure for full pipeline and adapt. Most Important: Handle data inputs (some API, some require download)
